version: '3'

services:

  queue:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - network

  db:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=stockboy
      - POSTGRES_PASSWORD=stockboy
      - POSTGRES_DB=stockboy
    ports:
      - 5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network

  transaction_consumer:
    image: python:3.8-slim-buster
    depends_on:
      - db
      - queue
    restart: on-failure
    links:
      - db:db
    networks:
      - network
    volumes:
      - ./transaction_consumer:/service
    entrypoint: ['sh', '/service/entrypoint.sh']

  upc_lookup:
    image: python:3.8-slim-buster
    depends_on:
      - db
      - queue
    restart: on-failure
    links:
      - db:db
    networks:
      - network
    volumes:
      - ./upc_lookup:/service
    entrypoint: ['sh', '/service/entrypoint.sh']

  scanner:
    image: python:3.8-slim-buster
    depends_on:
      - db
      - queue
    restart: on-failure
    networks:
      - network
    volumes:
      - ./scanner:/service
    entrypoint: ['sh', '/service/entrypoint.sh']

  frontend:
    image: python:3.8-slim-buster
    depends_on:
      - db
      - api
    restart: on-failure
    links:
      - db:db
    ports:
      - 8050:8050
    networks:
      - network
    volumes:
      - ./frontend:/service
    entrypoint: ['sh', '/service/entrypoint.sh']

  scanner:
    image: python:3.8-slim-buster
    depends_on:
      - db
      - queue
    restart: on-failure
    networks:
      - network
    volumes:
      - ./scanner:/service
    entrypoint: ['sh', '/service/entrypoint.sh']

  api:
    image: python:3.8-slim-buster
    depends_on:
      - db
    environment:
      - POSTGRES_USER=stockboy
      - POSTGRES_PASSWORD=stockboy
      - POSTGRES_DB=stockboy
    restart: on-failure
    links:
      - db:db
    ports:
      - 5000:80
    networks:
      - network
    volumes:
      - ./api:/service
    entrypoint: ['sh', '/service/entrypoint.sh']

volumes:
     pgdata:

networks:
  network: {}
